services:
  - type: web
    name: idraw
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 2 --timeout 120 wsgi:app
    healthCheckPath: /health
